### ISSUE TITLE
print pdf

### ISSUE THREAD

**Issue by amirjo0on** [mazenrashed/Printooth#11]
hi,can print pdf file?

**Comment by turtlepile** [comment]
I'm also curious about this, thanks.

**Comment by Robys915** [comment]
I'm also curious about this .! Thank you .

**Comment by mazenrashed** [comment]
Hi all, 
Unfortunately, printooth is not support printing pdf files now,
We hope to support it soon.

**Comment by R3Pro** [comment]
any news about PDF printing?
