### ISSUE TITLE
Text not appearing

### ISSUE THREAD

**Issue by Phabbyrich** [mazenrashed/Printooth#12]
When I print no text appears when the paper comes out of the printer. What could be the problem?

**Comment by mazenrashed** [comment]
The paper roll could be inverted, try to install it correctly and tell me what you found.

**Comment by Phabbyrich** [comment]
I still got the same issue

**Comment by Phabbyrich** [comment]
add(RawPrintable.Builder(byteArrayOf(27, 100, 4)).build())

When I take off this line it doesn't work at all
When I add it it moves the paper roll but with no text

**Comment by mazenrashed** [comment]
Do you want to print text or what?

**Comment by Phabbyrich** [comment]
Yeah

**Comment by Phabbyrich** [comment]
Problem solved.
Changed the printer

**Comment by mazenrashed** [comment]
Good job,
and you can use TextPrintable instead of rowPrintable
var printable = TextPrintable.Builder() .setText("Hello World")

**Comment by NicolaCannata** [comment]
HI guys,
I have the same problem, i've tryed with different print but still the paper come out blank.
How can i solve this?

**Comment by NicolaCannata** [comment]
private void printText() {
        ArrayList<Printable> printables = new ArrayList<>();
        printables.add(new RawPrintable.Builder(new byte[]{27, 100, 4}).build());

        //Add Text
        printables.add(new TextPrintable.Builder()
                .setText("Hello World:")
                .setCharacterCode(DefaultPrinter.Companion.getCHARCODE_PC1252())
                .setNewLinesAfter(1)
                .build());
printing.print(printables);

I if delete rowprintable the paper even come out
