### ISSUE TITLE
ALIGNMENT_LEFT & ALIGNMENT_RIGHT

### ISSUE THREAD

**Issue by PokerAsh** [mazenrashed/Printooth#18]
The thing is TextPrintable with alignment_left without setting newLinesAfter makes text to move end.
For example, I want to align two texts at the same line. One with left alignment the next one right alignment.
```
    add(
            TextPrintable.Builder()
                .setText("${documentTitle}")
                .setCharacterCode(DefaultPrinter.CHARCODE_PC866)
                .setAlignment(DefaultPrinter.ALIGNMENT_LEFT)
                .build()
        )

        add(
            TextPrintable.Builder()
                .setText("${documentNumber}")
                .setCharacterCode(DefaultPrinter.CHARCODE_PC866)
                .setAlignment(DefaultPrinter.ALIGNMENT_RIGHT)
                .setLineSpacing(LINE_SPACING_1)
                .setNewLinesAfter(1)
                .build()
        )
```
This make whole both text align to right.

**Comment by mazenrashed** [comment]
remove setNewLinesAfter(1) and your problem will solve :)

**Comment by Fahad-Follow** [comment]
Hi The problem persist when trying to display image on left and text on right on the same line. Here is my code.

    add(ImagePrintable.Builder(R.drawable.bill_app_icon1, resources)
            .setAlignment(DefaultPrinter.ALIGNMENT_LEFT)
            .build())
        add(TextPrintable.Builder()
            .setText("GHULAMULLAH DAIRYMILK")
            .setCharacterCode(DefaultPrinter.CHARCODE_PC437) //USA/Standard Europe
            .setAlignment(DefaultPrinter.ALIGNMENT_RIGHT)
            .setEmphasizedMode(DefaultPrinter.EMPHASIZED_MODE_BOLD)
            .setFontSize(DefaultPrinter.FONT_SIZE_NORMAL)
            .setUnderlined(DefaultPrinter.UNDERLINED_MODE_ON)        
            .build())
