### ISSUE TITLE
formatting words in a line

### ISSUE THREAD

**Issue by Chullian** [mazenrashed/Printooth#2]
is there any way to format a print like a shopping receipt like this?
[![screenshot from 2018-11-22 17-40-44](https://user-images.githubusercontent.com/34369823/48906469-fabfda00-ee7d-11e8-9cbe-a8e1b12a0d71.png)
](url)

**Comment by ekhiw** [comment]
This is fantastic library, really easy to use, but i cant find way to print text aside from image.
maybe it relate to this format.

Thank you for making a very useful library.

**Comment by mazenrashed** [comment]
@ekhiw Sorry but at some times it's up to the kind of printer you use,
And I'll review it in the next releases.
Please support Printooth with a star, Your welcome and good luck.

**Comment by mazenrashed** [comment]
@Chullian You need to use Java regular expiration
This is a sample : 
https://stackoverflow.com/questions/26803877/java-formatter-receipt-printing-issue

**Comment by welkinakash5** [comment]
Thanks @mazenrashed  for this usefull library  in turn for saving my JOB
