### ISSUE TITLE
Not showing list of Unpaired devices

### ISSUE THREAD

**Issue by ajmeraaxesh** [mazenrashed/Printooth#20]
Hi,
When initiating the intent for Scanning Acitivty. Is it only supposed to show a list of devices that have been previously paired in the past or is it suppose to show all the list of devices. 

Here is my java code
 Intent scanDeviceIntent = new Intent(this, ScanningActivity.class);               
 startActivityForResult(scanDeviceIntent, ScanningActivity.SCANNING_FOR_PRINTER);  

@Override                                                                                          
protected void onActivityResult(int requestCode, int resultCode, Intent data) {                    
    if (requestCode == ScanningActivity.SCANNING_FOR_PRINTER && resultCode == Activity.RESULT_OK) {
        Log.e(TAG, "Scan completed:: ");                                                           
        PairedPrinter pairedDevices = Printooth.INSTANCE.getPairedPrinter();                       
        Log.i(TAG, "name: " + pairedDevices.getName());                                            
        TextView printerName = (TextView) findViewById(R.id.printerName);                          
        printerName.setText(pairedDevices.getName());                                              
    }                                                                                              
}                                                                                                  

In the list of devices, I cannot see any devices even though bluetooth is on for other devices around

**Comment by mazenrashed** [comment]
Released in v. 1.2.2,
Your welcome!
