### ISSUE TITLE
Text dont print, the paper comes out blank

### ISSUE THREAD

**Issue by NicolaCannata** [mazenrashed/Printooth#22]
Hi,
How i said in the title, i implement the printooth code to print in my android studio app, i follow every step but when i go to print, the printer roll out the blank white paper but dont write anything.
How can i solve? i try different printer but still the same problem

**Comment by PokerAsh** [comment]
Are you trying to print Latin characters? 
The thing is different printers have different Unicode.

**Comment by mazenrashed** [comment]
Can you try to flip the paper roll ?
