### ISSUE TITLE
Missing Permission for app targets Android 9 (API level 28)

### ISSUE THREAD

**Issue by KelvinPac** [mazenrashed/Printooth#27]
Hi. For Apps targetting API 28 they need to declare location permissions
` <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`  to be able to scan for devices. If app has not requested this permisson the ScanningActivity can only see already paired devices.
This permission can be included in the app or somewhere in the ReadMe

**Comment by mazenrashed** [comment]
Thanks, I will do that.

**Comment by KelvinPac** [comment]
Welcome

**Comment by mazenrashed** [comment]
Released in v. 1.2.2,
Your welcome!

**Comment by KelvinPac** [comment]
Thank you. will check it out. Out of this issue, How do I reduce line spacing. I can't seem to figure that out. Am using Java
