### ISSUE TITLE
Printing Image or QR-code

### ISSUE THREAD

**Issue by RAZA-ABBBASI** [mazenrashed/Printooth#3]
Respected Developer,
First of all i want to say thank you to you for this easy to use library. I want to know, how we can print images or QR code using this library ?

**Comment by mazenrashed** [comment]
This feature is not available now, be honest to make a pull request to apply it 😊

**Comment by RAZA-ABBBASI** [comment]
Ok bosssss,
i will do it.

**Comment by mazenrashed** [comment]
Printooth is support printing images now, you can try it

**Comment by dittadsp** [comment]
hello ,
i have implemented QRCode with printooth , but somehow i couldn't scan the QR code due to the size is too small, can anyone help?
