### ISSUE TITLE
Image Alignment

### ISSUE THREAD

**Issue by joeldunamis** [mazenrashed/Printooth#34]
I'm trying to print image with center alignment, but whatever alignment I set on my ImagePrintable, the image result is always aligning to the left, while the TextPrintable alignment works just as intended. 

Is there anything else that I should add to my code to make the image appear on the center?

Here's my code:

            ArrayList<Printable> al = new ArrayList<>();
            Resources resources = getResources();           

            Bitmap image = BitmapFactory.decodeResource(resources,R.drawable.logo);
            al.add(new ImagePrintable.Builder(image)
                    .setAlignment(DefaultPrinter.Companion.getALIGNMENT_CENTER())
                    .setNewLinesAfter(1)
                    .build());

            al.add( (new TextPrintable.Builder())
                    .setText(" Hello World")
                    .setAlignment(DefaultPrinter.Companion.getALIGNMENT_CENTER())
                    .setNewLinesAfter(1)
                    .build());

            printing.print(al);

**Comment by mazenrashed** [comment]
Hi @joeldunamis , is the image dimensions is'nt have a hidden spaces?

**Comment by yulianto1992** [comment]
My image doesn't have any extra transparent space around the image itself. It was just a google play icon (the one that shaped like play button).  The resolution is pretty standard as far as an icon would go (tiny and has the same width and height).

**Comment by joeldunamis** [comment]
My image doesn't have any extra transparent space around the image itself. It was just a google play icon (the one that shaped like play button). The resolution is pretty standard as far as an icon would go (tiny and has the same width and height).

**Comment by mazenrashed** [comment]
You can read the documentation of your printer to solve the issue by send the correct command.
