### ISSUE TITLE
Printer prints again after bluetooth reset 

### ISSUE THREAD

**Issue by Steban23m** [mazenrashed/Printooth#37]
Hi, 
I was trying Printooth in a proyect I'm working on. I was able to use the library with a bluetooth printer, but there is a problem. My code schedules to reset ( off  /on)  the bluetooth after a few minutes and, if I've printed something before, my printer prints again the same thing without sending the order.

This are the steps of the code:
1. Initialize app.
2. Pair Printer with Scanned Device List
3. Button -> print some text.
4. Bluetooth reset (OFF / ON)
5. Printer prints again.

I don't know if is an issue with the library that doesn't close the BT conection or It's just my printer that has this behaviour.

Here is the code of the printing scenario: 

`     PairedPrinter printer = Printooth.INSTANCE.getPairedPrinter();

            ArrayList<Printable> printables =  new ArrayList<>();
            Printable printable = new TextPrintable.Builder()
                    .setText("Hello World" )
                   
                    .build();
            printables.add(printable);
      
            Printooth.INSTANCE.printer().print(printables);
       `

Thanks in advance.

**Comment by mazenrashed** [comment]
I think that the printer has cached the orders, the lib isn't stored any printing order.

**Comment by Amirnadi** [comment]
Hi, didn't get that. How I can stop it from printing again after bluetooth reset ?

**Comment by RodrigoSolanoMarques** [comment]
I solved this problem instancing "prostooth.init (context)" in acitivity instead of the application class.
I think the method "removeCurrentPrinter" remove of the lib, but does not remove the connection to the system.
