### ISSUE TITLE
How to check if paired printer is currently connected/active.

### ISSUE THREAD

**Issue by codedentwickler** [mazenrashed/Printooth#47]
Thank you for this awesome library @mazenrashed . Is there a way I can check if the last paired printer is active. Something like an `isConnected()` call. 

Is there a way I can do this before attempting to print?

**Comment by pear9** [comment]
hey @codedentwickler can you please share your project done using this library...
been stuck for several days...

**Comment by codedentwickler** [comment]
Hi @pear9, I can't share the project as it is for my company but I will be happy to help you. What are the issues you're facing? Have you tried looking into the example app?

Someone also contributed a java project so you can use that if your project is java based. https://github.com/lafras-h/JavaPrintooth

**Comment by edinofricaniago** [comment]
You can check the paired printer is active or not with `BluetoothDevice.BOND_BONDED`
reference code in this library
https://github.com/mazenrashed/Printooth/blob/678b111643726f76471b9b0e7905b832cb8f05bc/printooth/src/main/java/com/mazenrashed/printooth/ui/ScanningActivity.kt#L93-L99

and this is how I implement it in my code, always check when `android.bluetooth.adapter.action.STATE_CHANGED` , `android.bluetooth.device.action.ACL_CONNECTED` , `android.bluetooth.device.action.ACL_DISCONNECTED`
```
val device: BluetoothDevice = bluetoothAdapter.getRemoteDevice(
    Printooth.getPairedPrinter()?.address
)

if (device.bondState == BluetoothDevice.BOND_BONDED) {
    isConnect = true
} else {
    isConnect = false
}
```
hopefully can help you 😊

**Comment by codedentwickler** [comment]
@edinofricaniago Thank you
