### ISSUE TITLE
Android-x Support 

### ISSUE THREAD

**Issue by gzodx** [mazenrashed/Printooth#48]
android.support.v4.widget.SwipeRefreshLayout changed to => androidx.swiperefreshlayout.widget.SwipeRefreshLayout

**Comment by gzodx** [comment]
it crashes on when trying to call the scanner Activity on any apps that uses androidx 
Unable to start activity ComponentInfo{com.example.testingprint/com.mazenrashed.printooth.ui.ScanningActivity}: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class androidx.swiperefreshlayout.widget.SwipeRefreshLayout

**Comment by Rick19** [comment]
The problem remains the same, even with androidx.swiperefreshlayout.widget.SwipeRefreshLayout from android.support.v4.widget.SwipeRefreshLayout 

------
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout"
------

**Comment by Dakusy** [comment]
have you added     implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0" ?

**Comment by gzodx** [comment]
I had to fix it my self for my personal use but I can could raise or to this

**Comment by mazenrashed** [comment]
Fixed in 1.2.2.
