### ISSUE TITLE
ScanningActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by RikySaepuloh** [mazenrashed/Printooth#51]
this problem was triggered when user tries to select a bluetooth device during the scan.
It looks like you forgot to call unregisterReceiver().

`Activity com.mazenrashed.printooth.ui.ScanningActivity has leaked IntentReceiver com.mazenrashed.printooth.utilities.Bluetooth$3@4ee1a0b that was originally registered here. Are you missing a call to unregisterReceiver()?`

or am i forget to initialized something ?

**Comment by mazenrashed** [comment]
No, It's called in onStop(), 
But the issue caused by another issue, Can you check v 1.2.2?
It's solved now inshallah.

**Comment by RikySaepuloh** [comment]
@mazenrashed mashaallah, thank you... i'll try to fix it in my project
