### ISSUE TITLE
what is the value for variable LAST_VERSION 

### ISSUE THREAD

**Issue by Fahad-Follow** [mazenrashed/Printooth#54]
unable to find value of variable LAST_VERSION in

 implementation 'com.github.mazenrashed:Printooth:${LAST_VERSION}'

I am currently unable to add library because I do not know the version of library.

**Comment by dikahasyim** [comment]
implementation 'com.github.mazenrashed:Printooth:1.2.1'

1.2.1 is the latest version

**Comment by Fahad-Follow** [comment]
thank you dear
