### ISSUE TITLE
Charecter encoding

### ISSUE THREAD

**Issue by JcDenton86** [mazenrashed/Printooth#7]
Hi,

Thanks for this library. I set it up on my Android project and successfully printing English characters. How can I sen another code page encoding? 

I' ve seen on DefaultPrinter.kt how you define some `Byte` vars like `CHARACTER_CODE_ARABIC_CP720`.

How can I define for a different Language other than Arabic or English?

Thank you in advance

**Comment by mazenrashed** [comment]
Hi, 
You need to go to your printer commands sheet and take a look for encodings,
This is a sample from Sewoo commands sheet (command manual) :

https://www.manualslib.com/manual/1143898/Sewoo-Lk-P41.html?page=27#manual

Then, when you initialize a printable, 
```kotlin
var printable = Printable.PrintableBuilder()  
        .setText("Hello World")
        .setCharacterCode(YOUR CHARTERER CODE) 
        .build()
```

I hope to put a star for Printooth if its helpful for you, Good luck.

**Comment by JcDenton86** [comment]
Hi and thanks for your response!

I already stared this library because it is indeed helpful! 

I ve read the documentation and my question is on your answer. for instance if I want to use 'cp1253', what should I put as parameter on the `setCharacterEncoding` function. I cannot find the mappings somewhere between character encoding and bytes

Thank you again

**Comment by ZakariaJawas** [comment]
@JcDenton86 
There is a group of encoding bytes already defined inside DefaultPrinter class
for example you can pass
**DefaultPrinter.CHARCODE_PC1252** 
by the way PC1253  is not predefined so you have the ask the printer provider for the byte representation of your required encoding
Ex: PC1252 is "0x10" as defined in the library
