### ISSUE TITLE
New Logo for Printooth

### ISSUE THREAD

**Issue by Yasujizr** [mazenrashed/Printooth#8]
Hi, 

I'm doing logo for open source projects. When I was doing research at Github, I saw your project. If you want, we can design a logo according to your wishes.

cheers.

**Comment by mazenrashed** [comment]
Hi @Yasujizr ,
Thank you very much, of course, we can do it 🥇 .

**Comment by mazenrashed** [comment]
Hi @Yasujizr 
Please let me know if you are still interested.

**Comment by Yasujizr** [comment]
Of course @mazenrashed 

Let's start if you give a brief for the design. Theme, color, line, examples of your favorite design.

**Comment by mazenrashed** [comment]
Thank you for kindness, I hope to work together in the future.
