### ISSUE TITLE
Paperdb repository update

### ISSUE THREAD

**Issue by ndptra** [mazenrashed/Printooth#92]
Hi, could you please update paperdb repository to "io github.plgr."? It seems like printooth is unusable because of it. As stated from paper github: 
'Library has been moved to Maven Central since service ends for JCenter. Note that group id has been changed to io.github.pilgr.'

I keep getting errors on build when using printooth

**Comment by ndptra** [comment]
nevermind, it was my fault. Didn't set the repositories correctly on build.gradle

**Comment by andrefvneto** [comment]
Hi, what implementation did you use? Thanks
