### ISSUE TITLE
Could not resolve all files for configuration ':app:debugRuntimeClasspath'. error

### ISSUE THREAD

**Issue by noj-dev** [mazenrashed/Printooth#95]
Hi, I make new empty project and install Printooth by setting build.gradle.
1:add "implementation 'com.github.mazenrashed:printooth:1.3.0' " to build.gradle(Module)
2:add "maven { url 'https://jitpack.io' }" to setting.gradle

environment
AndroidStudio Bumblebee

When I run the project , error appears like below:
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

Do you have any idea for this issue ?

**Comment by arinmodi** [comment]
I also faced the same problem

**Comment by arinmodi** [comment]
@noj-dev, did you find any solution ?

**Comment by noj-dev** [comment]
I created new project with older version of Android Studio and installed Printooth.
Then open the project with newer Android Studio.
For me it works
